//tag::vardef[]
:gh-repo-owner: jmini
:gh-repo-name: sync-eclipse-settings-example

:project-name: Sync eclipse-settings example
:git-branch: master
:twitter-handle: j2r2b
:license: http://www.eclipse.org/legal/epl-v10.html
:license-name: Eclipse Public License - v 1.0

:git-repository: {gh-repo-owner}/{gh-repo-name}
:homepage: https://{gh-repo-owner}.github.io/{gh-repo-name}
:issues: https://github.com/{git-repository}/issues
:example-folder-name: example-use
:example-folder-url: https://github.com/{git-repository}/tree/{git-branch}/{example-folder-name}
//end::vardef[]

//tag::header[]
= {project-name}
Example usages of the eclipse-settings-maven-plugin
//end::header[]

//tag::description[]
== Description
This repository demonstrates how you can use the goal `eclipse-settings` of the link:https://mvnrepository.com/artifact/org.eclipse.scout/eclipse-settings-maven-plugin[eclipse-settings-maven-plugin] to synchronize the eclipse-settings files between multiple project.
The `*.prefs` files stored inside a maven artifact are extracted each `.setting` folder of each project using the maven plugin.

This repository provides some example projects that use the maven plugin.
They are located in the link:{example-folder-url}[{example-folder-name}] folder.

//end::description[]
Read more on the link:{homepage}[project home page].

//tag::contact-section[]
== Get in touch

Use the link:{issues}[{project-name} issue tracker] on GitHub.

You can also contact me on Twitter: link:https://twitter.com/{twitter-handle}[@{twitter-handle}]
//end::contact-section[]

//tag::license-section[]
== License

link:{license}[{license-name}]
//end::license-section[]
